mono_source/config/routes.rb
CMS::Application.routes.draw do

  get "about/index"

  resource :reporte

  resources :variables

  resources :pruebas

  resources :compuerta_pre_desicions

  resources :compuerta_desicions

  resources :tarea_aprobacions

  resources :tarea_revisions

  resources :actividad_revisions

  devise_for :users

  resources :tarea_artefactos

  resources :estado_tareas

  resources :tarea_participantes

  resources :tarea_presedencia

  resources :tarea_recursos

  resources :tareas

  resources :tipo_organizacions

  resources :proyecto_artefactos

  resources :artefactos

  resources :proyecto_usuarios

  resources :proyecto_recursos

  resources :proyecto_organizacions

  resources :transicions

  resources :procesos

  resources :usuarios

  resources :actividad_rols

  resources :actividad_tipoartefactos

  resources :tipo_artefactos

  resources :ruta

  resources :eventos

  resources :my_js_trees

  resources :actividad_tiporecursos

  resources :compuertus

  resources :compuerta

  resources :actividads

  resources :plantillas

  resources :tipo_plantillas

  resources :recursos

  resources :tipo_recursos

  resources :organizacions

  resources :rols

  resources :proyectos

  resources :tipo_productos

  resources :archivo_proyectos

  resources :archivos

  resources :tipo_archivos

  resources :deposito_proyectos

  resources :depositos

  resources :tipo_depositos

  resources :assignments

  resources :workers

  resources :projects

  resources :loops

  resources :merges

  resources :calendarios

  match '/about' => 'about#index'

  match '*all' => 'application#cors_preflight_check', :constraints => {:method => 'OPTIONS'}
  match '/reporte/:id_proyecto/proyecto' => 'reporte#proyecto'
  match '/reporte/:id_proceso/procesos' => 'reporte#procesos'

  match '/local/:id/use' => 'local#use'
  match '/local/:id/upload' => 'local#upload'
  match '/mediabrowser' => 'mediabrowser#list', :as => :discolocal
  match '/mediabrowser' => 'mediabrowser#list', :as => :mediabrowser
  match '/mediabrowser/delete' => 'mediabrowser#delete', :as => :delete_file_mediabrowser
  match '/mediabrowser/dir/create'  => 'mediabrowser#create_dir',  :as => :create_dir_mediabrowser
  match '/mediabrowser/file/create'  => 'mediabrowser#create_file',  :as => :create_file_mediabrowser

  match '/indexUsuario' => 'index#indexUsuario', :as => 'indexUsuario'
  match '/graficas' => 'index#graficas', :as => 'graficas'

  match '/tipo_recursos/existe/nombre' => 'tipo_recursos#existe', :as => :validacion_existe
  match '/recursos/existe/nombre' => 'recursos#existe', :as => :validacion_existe
  match '/tipo_plantillas/existe/nombre' => 'tipo_plantillas#existe', :as => :validacion_existe
  match '/tipo_organizacions/existe/nombre' => 'tipo_organizacions#existe', :as => :validacion_existe
  match '/plantillas/existe/nombre' => 'plantillas#existe', :as => :validacion_existe
  match '/tipo_artefactos/existe/nombre' => 'tipo_artefactos#existe', :as => :validacion_existe
  match '/actividads/existe/:nombre/:plantilla' => 'plantillas#existe', :as => :validacion_existe
  match '/actividads_turnos' => 'actividads#turnos', :as => :turnos # agregar turnos
  match '/actividad_revisor' => 'tarea_revisions#revisor', :as => :revisor # asignar revisores
  match '/compuerta_options' => 'compuerta_desicions#options', :as => :options #opciones compuerta
  match '/proyectos/existe/nombre' => 'proyectos#existe', :as => :validacion_existe
  match '/actividad_tiporecursos/existe/nombre' => 'actividad_tiporecursos#existe', :as => :validacion_existe
  match '/actividad_tipoartefactos/existe/nombre' => 'actividad_tipoartefactos#existe', :as => :validacion_existe
  match '/usuarios/existe/login' => 'usuarios#existe', :as => :validacion_existe
  match '/usuarios/password_iguales/pasword' => 'usuarios#password_iguales', :as => :validacion_password_iguales
  match '/rols/existe/nombre' => 'rols#existe', :as => :validacion_existe
  match '/organizacions/existe/nombre' => 'organizacions#existe', :as => :validacion_existe
  match '/organizacions/existe/nit' => 'organizacions#existenit', :as => :validacion_existenit
  match 'organizacions/existe/representante' => 'organizacions#existerepresentante', :as => :validacion_existerepresentante
  match 'organizacions/unico/representante' => 'organizacions#unicorepresentante', :as => :validacion_unicorepresentante

  match '/depositos/existe/nombre' => 'depositos#existe', :as => :validacion_existe

  match '/proyectos/:id/configu' => 'proyectos#configu', :as => :configu
  match '/proyectos/:id/configuempr' => 'proyectos#configuempr', :as => :configuempr
  match '/proyectos/:id/configupart' => 'proyectos#configupart', :as => :configupart
  match '/proyectos/:id/overview' => 'proyectos#overview', :as => :overview
  match '/proyectos/:id/priorizar' => 'proyectos#priorizar', :as => :priorizar
  match '/proyectos/:id/actualizarPriorizacion' => 'proyectos#actualizarPriorizacion', :as => :actualizarPriorizacion
  match '/proyectos/:id/actualizarPrior' => 'proyectos#actualizarPrior', :as => :actualizarPrior

  match '/proyectos/:id/priorizarTareas/:idusuario' => 'proyectos#priorizarTareas', :as => :priorizarTareas
  match '/proyectos/:id/arbol' => 'proyectos#arbol', :as => :arbol

  match   '/trees', :to => 'my_js_trees#jstree'
  match   '/treedata', :to => 'my_js_trees#jstreedata'

  match '/actividads/:id/destroy' => 'actividads#destroy', :as => :destroy
  match '/compuertus/:id/destroy' => 'compuertus#destroy', :as => :destroy
  match '/eventos/:id/destroy' => 'eventos#destroy', :as => :destroy
  match '/ruta/:id/destroy' => 'ruta#destroy', :as => :destroy
  match '/merges/:id/destroy' => 'merges#destroy', :as => :destroy
  match '/loops/:id/destroy' => 'loops#destroy', :as => :destroy

  match '/actividads/:id/updateName' => 'actividads#updateName', :as => :update
  match '/actividads/:id/updateType' => 'actividads#updateType', :as => :update
  match '/compuertus/:id/updateName' => 'compuertus#updateName', :as => :update
  match '/compuertus/:id/updateType' => 'compuertus#updateType', :as => :update

  match '/loops/:id/updateName' => 'loops#updateName', :as => :updateName
  match '/eventos/:id/updateName' => 'eventos#updateName', :as => :update
  match '/ruta/:id/updateName' => 'ruta#updateName', :as => :update
  match '/my_js_trees/:id/updateParent' => 'my_js_trees#updateParent', :as => :update

  match '/tarea_participantes/:id/updateEstado' => 'tarea_participantes#updateEstado', :as => :updateEstado
  match '/tarea_participantes/:id/updateHoras' => 'tarea_participantes#updateHoras', :as => :updateHoras

  match '/procesos/clonar_plantilla/:id_plantilla/:id_proyecto' => 'procesos#clonar_plantilla', :as => :clonar_plantilla

  match '/procesos/getTipoPlantilla/all' => 'procesos#getTipoPlantilla', :as => :getTipoPlantilla
  match '/procesos/getdata/:tipo_plantilla' => 'procesos#getdata', :as => :getdata
  match '/proyecto_organizacions/get_tipo_organizacions/all' => 'proyecto_organizacions#get_tipo_organizacions', :as => :get_tipo_organizacions
  match '/proyecto_organizacions/get_organizacions/:tipo_organizacion_id' => 'proyecto_organizacions#get_organizacions', :as => :get_organizacions
  match '/proyectos/get_organizaciones/all' => 'proyectos#get_organizaciones', :as => :get_organizaciones
  match '/proyectos/get_usuarios_org/:organizacion_id' => 'proyectos#get_usuarios_org', :as => :get_usuarios_org
  match '/depositos/get_tipo_depositos/all' => 'depositos#get_tipo_depositos', :as => :get_tipo_depositos
  match '/proyectos/getTipoRecurso/:id' => 'proyectos#getTipoRecurso', :as => :getTipoRecurso
  match '/proyectos/getdata/:id/:tipo_recurso' => 'proyectos#getdata', :as => :getdata

  match '/proyectos/listar_procesos/:id/:proy_id' => 'proyectos#listar_procesos', :as => :listar_procesos

  match '/procesos/:id/get_optimizar' => 'procesos#get_optimizar', :as => :get_optimizar
  match '/procesos/:id_proceso/crear_procesoopt' => 'procesos#crear_procesoopt', :as => :crear_procesoopt
  match '/procesos/:id_proceso/crear_procesooptimi' => 'procesos#crear_procesooptimi', :as => :crear_procesooptimi

  match "/procesos/:id_proceso/icons/:id", :to => redirect("/assets/%{id}.png")
  match "/procesos/:id_proceso/css/:id", :to => redirect("/assets/%{id}.css")
  match "/procesos/:id_proceso/scripts/:id", :to => redirect("/assets/%{id}.js")

  match '/procesos/:id_proceso/xpdl' => 'procesos#GenerateXPDL', :as => :GenerateXPDL
  match '/plantillas/:id_plantilla/xpdl' => 'plantillas#GenerateXPDL', :as => :GenerateXPDL

  match '/procesos/:id_proceso/icons/:pag', :to => redirect('/assets/'||:pag)
  match '/procesos/:id_proceso/css/:pag', :to => redirect('/assets/'||:pag)
  match '/procesos/:id_proceso/scripts/:pag', :to => redirect('assets/'||:pag)

  match '/procesos/:id_proceso/crear_programa' => 'procesos#crear_programa', :as => :crear_programa
  match '/procesos/:id_proceso/aprobaciones' => 'procesos#aprobaciones', :as => :aprobaciones
  match '/tareas/:id_tarea/asignar_responsable' => 'tareas#asignar_responsable', :as => :asignar_responsable
  match '/tareas/:id_tarea/actualizar_tarea' => 'tareas#actualizar_tarea', :as => :actualizar_tarea
  match '/tareas/:id_tarea/get_json_data' => 'tareas#get_json_data', :as => :get_json_data
  match '/calendarios/:id_calendario/actualizar_calendario' => 'calendarios#actualizar_calendario', :as => :actualizar_calendario

  match '/artefactos/:dummy/search_assets' => 'artefactos#search_assets', :as => :search_assets
  match '/basecamp/:id/get_proyectos' => 'basecamp#get_proyectos', :as => :get_proyectos
  match '/deposito_proyectos/:id/new' => 'deposito_proyectos#new', :as => :nuevoDeposito
  match '/archivo_proyectos/:id/new' => 'archivo_proyectos#new', :as => :nuevoArchivo
  match '/dropbox/:id/autenticar' => 'dropbox#autenticar',:as => :dropbox
  match '/dropbox/use' => 'dropbox#use'   ,:as => :dropboxU ,:layout => 'actividads'
  match '/basecamp/:id/use' => 'basecamp#use' ,:as => :basecamp

mono_source/app/models/compuerta_pre_desicion.rb
=begin
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end
class CompuertaPreDesicion < ActiveRecord::Base
  belongs_to :compuertu, :foreign_key => 'compuerta_id'
  belongs_to :rutum, :foreign_key => 'ruta_id'
  belongs_to :tarea, :foreign_key => 'tarea_desicion_id'

  attr_accessible :compuerta_id, :elegida, :id, :ruta_id, :tarea_desicion_id
end

mono_source/app/controllers/compuerta_pre_desicions_controller.rb
=begin
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end
class CompuertaPreDesicionsController < ApplicationController
  # GET /compuerta_pre_desicions
  # GET /compuerta_pre_desicions.json
  def index
    @compuerta_pre_desicions = CompuertaPreDesicion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @compuerta_pre_desicions }
    end
  end

  # GET /compuerta_pre_desicions/1
  # GET /compuerta_pre_desicions/1.json
  def show
    @compuerta_pre_desicion = CompuertaPreDesicion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @compuerta_pre_desicion }
    end
  end

  # GET /compuerta_pre_desicions/new
  # GET /compuerta_pre_desicions/new.json
  def new
    @compuerta_pre_desicion = CompuertaPreDesicion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @compuerta_pre_desicion }
    end
  end

  # GET /compuerta_pre_desicions/1/edit
  def edit
    @compuerta_pre_desicion = CompuertaPreDesicion.find(params[:id])
  end

  # POST /compuerta_pre_desicions
  # POST /compuerta_pre_desicions.json
  def create


    params[:cantidad].to_i.times do |count|

      if params[:compuerta_pre]
        @compuerta_pre_desicion = CompuertaPreDesicion.find(params[:compuerta_pre][count.to_s])
      else
        @compuerta_pre_desicion = CompuertaPreDesicion.new
      end

      @compuerta_pre_desicion.compuerta_id = params[:compuerta_id]
      @compuerta_pre_desicion.tarea_desicion_id = params[:tarea_desicion_id]
      @compuerta_pre_desicion.ruta_id = params[:compuerta_ruta][count.to_s]
      if params[:compuerta_type] == 'compuerta_exclu'
        @compuerta_pre_desicion.elegida = params[:compuerta_ruta][count.to_s] == params[:elegida]
      else
        if params[:ruta]
          @compuerta_pre_desicion.elegida = params[:compuerta_ruta][count.to_s] == params[:ruta][count.to_s]
        else
          @compuerta_pre_desicion.elegida = false
        end

      end

      @compuerta_pre_desicion.save

    end
    #@compuerta_pre_desicion = CompuertaPreDesicion.new(params[:compuerta_pre_desicion])

    respond_to do |format|
      if @compuerta_pre_desicion.save
        format.html { redirect_to "/tarea_participantes", notice: 'Compuerta pre desicion was successfully created.' }
        format.json { render json: @compuerta_pre_desicion, status: :created, location: @compuerta_pre_desicion }
      else
        format.html { render action: "new" }
        format.json { render json: @compuerta_pre_desicion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /compuerta_pre_desicions/1
  # PUT /compuerta_pre_desicions/1.json
  def update
    @compuerta_pre_desicion = CompuertaPreDesicion.find(params[:id])

    respond_to do |format|
      if @compuerta_pre_desicion.update_attributes(params[:compuerta_pre_desicion])
        format.html { redirect_to @compuerta_pre_desicion, notice: 'Compuerta pre desicion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @compuerta_pre_desicion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compuerta_pre_desicions/1
  # DELETE /compuerta_pre_desicions/1.json
  def destroy
    @compuerta_pre_desicion = CompuertaPreDesicion.find(params[:id])
    @compuerta_pre_desicion.destroy

    respond_to do |format|
      format.html { redirect_to compuerta_pre_desicions_url }
      format.json { head :no_content }
    end
  end
end

mono_source/app/views/compuerta_pre_desicions/_form.html.erb
<!--
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<%= form_for(@compuerta_pre_desicion) do |f| %>
  <% if @compuerta_pre_desicion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compuerta_pre_desicion.errors.count, "error") %> prohibited this compuerta_pre_desicion from being saved:</h2>

      <ul>
      <% @compuerta_pre_desicion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :compuerta_id %><br />
    <%= f.number_field :compuerta_id %>
  </div>
  <div class="field">
    <%= f.label :ruta_id %><br />
    <%= f.number_field :ruta_id %>
  </div>
  <div class="field">
    <%= f.label :elegida %><br />
    <%= f.check_box :elegida %>
  </div>
  <div class="field">
    <%= f.label :tarea_desicion_id %><br />
    <%= f.number_field :tarea_desicion_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mono_source/app/views/compuerta_pre_desicions/edit.html.erb
<!--
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<h1>Editing compuerta_pre_desicion</h1>

<%= render 'form' %>

<%= link_to 'Show', @compuerta_pre_desicion %> |
<%= link_to 'Back', compuerta_pre_desicions_path %>

mono_source/app/views/compuerta_pre_desicions/index.html.erb
<!--
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<h1>Listing compuerta_pre_desicions</h1>

<table>
  <tr>
    <th>Compuerta</th>
    <th>Ruta</th>
    <th>Elegida</th>
    <th>Tarea desicion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @compuerta_pre_desicions.each do |compuerta_pre_desicion| %>
  <tr>
    <td><%= compuerta_pre_desicion.compuerta_id %></td>
    <td><%= compuerta_pre_desicion.ruta_id %></td>
    <td><%= compuerta_pre_desicion.elegida %></td>
    <td><%= compuerta_pre_desicion.tarea_desicion_id %></td>
    <td><%= link_to 'Show', compuerta_pre_desicion %></td>
    <td><%= link_to 'Edit', edit_compuerta_pre_desicion_path(compuerta_pre_desicion) %></td>
    <td><%= link_to 'Destroy', compuerta_pre_desicion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Compuerta pre desicion', new_compuerta_pre_desicion_path %>

mono_source/app/views/compuerta_pre_desicions/new.html.erb
<!--
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<h1>New compuerta_pre_desicion</h1>

<%= render 'form' %>

<%= link_to 'Back', compuerta_pre_desicions_path %>

mono_source/app/views/compuerta_pre_desicions/show.html.erb
<!--
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<p id="notice"><%= notice %></p>

<p>
  <b>Compuerta:</b>
  <%= @compuerta_pre_desicion.compuerta_id %>
</p>

<p>
  <b>Ruta:</b>
  <%= @compuerta_pre_desicion.ruta_id %>
</p>

<p>
  <b>Elegida:</b>
  <%= @compuerta_pre_desicion.elegida %>
</p>

<p>
  <b>Tarea desicion:</b>
  <%= @compuerta_pre_desicion.tarea_desicion_id %>
</p>


<%= link_to 'Edit', edit_compuerta_pre_desicion_path(@compuerta_pre_desicion) %> |
<%= link_to 'Back', compuerta_pre_desicions_path %>